[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Clarify"
version = "0.5.0.dev0"
dependencies = [
    "requests",
    "cssselect",
    "requests-futures",
    "wheel"
]
